from telegram.ext import filters

SELECT_PAIR, INPUT_ITICK_TOKEN, SELECT_PRESETS, MONITORING = range(4)
PRESET_MENU, PRESET_CREATE_NAME, PRESET_CREATE_TICK, PRESET_CREATE_SIGNALS, PRESET_CREATE_FILTERS = range(4, 9)
AUTH_WAIT = 9

TEXT_MESSAGE_FILTER = filters.UpdateType.MESSAGE & filters.TEXT & ~filters.COMMAND
