from telegram.ext import filters

SELECT_PAIR, INPUT_ITICK_TOKEN, SELECT_TICK, SELECT_SIGNALS, SELECT_FILTERS, MONITORING = range(6)

TEXT_MESSAGE_FILTER = filters.UpdateType.MESSAGE & filters.TEXT & ~filters.COMMAND
